=== N-a-o-m-i/2016S1_DSA/DSA_Lab9_ReadXML/books.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
   <xsd:annotation>
      <xsd:documentation xml:lang="en">
         books.xsd XML Schema for defining a list of books
      </xsd:documentation>
   </xsd:annotation>

   <xsd:element name="books">
      <xsd:complexType>
         <xsd:sequence>
            <xsd:element name="description" type="xsd:string"
               minOccurs="0" maxOccurs="1"/>
            <xsd:element name="book" type="BookType"
               minOccurs="0" maxOccurs="unbounded"/>
         </xsd:sequence>
      </xsd:complexType>
   </xsd:element>

   <xsd:complexType name="BookType">
      <xsd:sequence>
         <xsd:element name="title" type="xsd:string"/>
         <xsd:element name="author" type="xsd:string"
            minOccurs="1" maxOccurs="unbounded"/>
         <xsd:element name="pub" minOccurs="0" maxOccurs="1">
            <xsd:complexType>
               <xsd:attribute name="name" type="xsd:string"
                  use="required"/>
               <xsd:attribute name="website" type="xsd:string"
                  use="optional"/>
            </xsd:complexType>
         </xsd:element>
      </xsd:sequence>
      
      <xsd:attribute name="isbn" type="xsd:string" use="required"/>
      
      <xsd:attribute name="cover" use="optional" default="hard">
        <xsd:simpleType>
           <xsd:restriction base="xsd:string">
              <xsd:enumeration value="hard"/>
              <xsd:enumeration value="soft"/>
           </xsd:restriction>
        </xsd:simpleType>
      </xsd:attribute>
      
      <xsd:attribute name="edition" type="xsd:positiveInteger"
         use="optional"/>
   </xsd:complexType>
</xsd:schema>

=== N-a-o-m-i/2016S1_DSA/DSA_Lab9_ReadXML/ComputerBooks.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- ComputerBooks.xml document of a list of computer books -->
<books
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:noNamespaceSchemaLocation="books.xsd">
   <description>
      Some useful books for second year computer science
   </description>
   <book isbn="0-321-24584-9" cover="soft" edition="2">
      <title>Java Software Structures</title>
      <author>John Lewis</author>
      <author>Joseph Chase</author>
      <pub name="Addison Wesley" website="http://www.aw-bc.com/"/>
   </book>
   <book isbn="0-02-354856-8" cover="hard" edition="2">
      <title>Computer Graphics Using OpenGL</title>
      <author>Francis Hill</author>
      <pub name="Prentice Hall" website="http://www.prenhall.com/"/>
   </book>
   <book isbn="0-262-03293-7" cover="soft" edition="2">
      <title>Introduction To Algorithms</title>
      <author>Thomas Corman</author>
      <author>Charles Leiserson</author>
      <author>Ronald Rivest</author>
      <author>Clifford Stein</author>
      <pub name="MIT Press" website="http://mitpress.mit.edu/"/>
   </book>
</books>
